name: generate_docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: 'write'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GOPROXY: "https://proxy.golang.org,direct"
      GONOSUMDB: "github.com/ioriver/*"
      GOPRIVATE: "github.com/ioriver"
    steps:
      - name: Source code checkout
        uses: actions/checkout@v4

      - name: Setup Go
        if: success()
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Install dependencies
        if: success()
        run: |
          go get

      - name: Install golangci-lint
        if: success()
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2

      - name: Lint code
        if: success()
        run: |
          golangci-lint run --fast

      - name: Generate docs
        if: success()
        run: |
          mkdir -p docs
          go generate ./...

      - name: Commit and Push Docs
        if: success()
        continue-on-error: true
        run: |
          git config user.name "devops"
          git config user.email "devops@ioriver.io"
          git add docs
          git commit -m "Update docs"
          git push

      - name: Trigger Master Workflow
        if: always()
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Use the GitHub API to trigger the target workflow
          curl -X POST -u $PAT_TOKEN: \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/master.yml/dispatches \
          -d '{"ref":"master"}'